# Site settings
paginate: 10
paginate_path: "page:num"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown
title: Will Anderson
description: Software Engineer

# User settings
author:
    name: Will Anderson
    email: will@willsa.io
    github: will-a
    linkedin: willsa
    bio: "<span style=\"color: #EF9860;\">RIT</span> Computer Science '22"

sidebar_image: /assets/profile_picture_2022.jpg

BASE_PATH: